//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandZone.PL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BandZoneEntities : DbContext
    {
        public BandZoneEntities()
            : base("name=BandZoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGenre> tblGenre { get; set; }
        public virtual DbSet<tblMusician> tblMusician { get; set; }
        public virtual DbSet<tblMusicianVenueEvent> tblMusicianVenueEvent { get; set; }
        public virtual DbSet<tblSong> tblSong { get; set; }
        public virtual DbSet<tblSongGenre> tblSongGenre { get; set; }
        public virtual DbSet<tblVenue> tblVenue { get; set; }
        public virtual DbSet<tblMusicGenre> tblMusicGenre { get; set; }
        public virtual DbSet<tblSearch> tblSearch { get; set; }
    }
}
