//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandZone.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusicGenre
    {
        public int Id { get; set; }
        public int MusicianId { get; set; }
        public int GenreId { get; set; }
    }
}
