//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandZone.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSongGenre
    {
        public System.Guid Id { get; set; }
        public System.Guid SongId { get; set; }
        public System.Guid GenreId { get; set; }
    }
}
