//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandZone.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVenue
    {
        public System.Guid VenueId { get; set; }
        public string LoginEmail { get; set; }
        public string Password { get; set; }
        public string VenueName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public string ContactEmail { get; set; }
        public string Phone { get; set; }
        public string ProfileImage { get; set; }
    }
}
