CREATE TABLE [dbo].[tblMusicianVenueEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [MusicianId] UNIQUEIDENTIFIER NOT NULL, 
    [VenueId] UNIQUEIDENTIFIER NOT NULL, 
    [EventTime] VARCHAR(50) NOT NULL
)
